### ISSUE TITLE
Error connecting if more than 10 PMUs are added to PDC stream.

### ISSUE THREAD

**Issue by shashankaum** [ALSETLab/S3DK#5]
![Error](https://user-images.githubusercontent.com/50229937/57124753-85e5ba00-6da4-11e9-95ef-2e9dcc5ea1f6.PNG)
I am using S3DK ver 1.5.0.5 with Labview 2018. the VI is working fine with output TCP stream created from PDC but as soon as i add more that 10 PMUs to the stream the VI shows error (screenshot attached).
I have tried other versions of S3DK also. Kindly help.

**Comment by lvanfretti** [comment]
It looks like your machine doesn’t have enough memory to handle all that amount of data.

To check, open the task manager and list the programs running while you repeat the experiment above.

Your only solution is to minimize memory use by only having the essential applications open, you should close all other memory intensive programs, e.g. Spotify, Chrome, Microsoft Office apps, etc. If that doesn’t help you probably need a computer with more RAM.

Good luck.

Luigi

**Comment by shashankaum** [comment]
I changed to different computer with 32 GB ram but the issue is persisting.

**Comment by lvanfretti** [comment]
Can you please use our PMU/PDC emulator to do the same test and share with us a step by step debugging report that we can replicate on our side?

https://github.com/ALSETLab/PMU-PDC-StreamSimulator

---
Sent from a mobile device.
Luigi Vanfretti, +1 (518) 496-0196

**Comment by shashankaum** [comment]
I tried with your PMU/PDC emulator and the S3DK connects fine and works well as long as 10 PMUs are added in PDC emulator, if i add the eleventh PMU the S3DK doesn't connects and the emulator crashes.
I am attaching a video of whole sequence for reference.
[Bug video (2).zip](https://github.com/ALSETLab/S3DK/files/3172487/Bug.video.2.zip)

**Comment by lvanfretti** [comment]
@shashankaum thanks for doing the debugging.
I'm not sure of what is going on so I will need help from some of my students to determine the errors. 

One thing I noticed is that around 0:28 sec in your video, the "Bad Data Quality Indicator" is showing 100%. 
<img width="1122" alt="Screenshot 2019-05-13 10 22 29" src="https://user-images.githubusercontent.com/7248948/57629014-08bb0180-7569-11e9-92da-2c75cd74e433.png">

Have you noticed this before? What this tells me is that the data generated by the emulator (PUPo) and the LabView layer is being dropped. This can be happening either at the S3DK DLL (which is underneath the LabVIEW layer/PRL), or the PRL itself.

If you are sending a fixed value for the frequency and you don't disable the error detection in the "Bad Data" tab of the PRL, this is probably one of the issues. Please turn it off.
<img width="365" alt="Screenshot 2019-05-13 10 25 06" src="https://user-images.githubusercontent.com/7248948/57629452-cfcf5c80-7569-11e9-9276-76d629d07f5b.png">

Next, the PRL is requesting to the S3DK to make Queues if the "Queue Active" and "Access Buffer Active" are selected. This is really efficient making queues within the S3DK DLL rather than in LabVIEW, but might be memory intensive anyway. Please unselected both choices, or make the queue and buffer very small.
<img width="373" alt="Screenshot 2019-05-13 10 25 23" src="https://user-images.githubusercontent.com/7248948/57629472-d8c02e00-7569-11e9-99d7-0fc4a88640e6.png">

Could you repeat the experiment above with the settings for the Bad Data and Buffers & Queues, and make a video using 2, 4, 6 PMUs, and also, what you did above? During the test, please have the task manager open to see what is going on with the memory consumption? 

Please share the configuration files you make for PUPo in order for my students to help.

@Grey-J and @prottay can you help reproducing the errors that @shashankaum is facing?

**Comment by shashankaum** [comment]
I repeated the experiment with access buffer active, queue active and bad data removal unchecked, but same thing happens as soon as i add eleventh PMU to stream S3DK fails to connect and emulator crashes. video attached for reference.
One more thing when i tried to form a aggregate stream in GE's PDC with limited/reduced number of analog and phasors selected per PMU then i am able to add more PMUs to stream and S3DK manages to connect successfully. seems something related to number of total analogs, phasors & digitals which S3DK can handle is limited.


[Bug video 2 converted.zip](https://github.com/ALSETLab/S3DK/files/3175870/Bug.video.2.converted.zip)
.

**Comment by lvanfretti** [comment]
Ok, so you have pinpointed the issue with the number of analogs, phasors and digitals.
Now, I am not sure if this issue is due to the S3DK DLL or due to LabVIEW.

My feeling is that the issue is with the LabVIEW part, passing the data from the DLL to LabVIEW; we may have some data type issue.

To test, can you use the the S3DK source to attempt a connection from the emulator and your GE PDC?
The repository is here: https://github.com/ALSETLab/S3DK-STRONGgrid

The stress test example is here:
https://github.com/ALSETLab/S3DK-STRONGgrid/tree/master/StrongridDLLStressTest

Please see the examples in the paper to establish a simple connection: https://www.sciencedirect.com/science/article/pii/S2352711018301705

@Grey-J and @prottay please see if you can help.

**Comment by shashankaum** [comment]
How do i change PDC mounted for test, port & PDCID in StrongridDLLStressTest.exe

**Comment by shashankaum** [comment]
I generated Log files from StrongridDLLStressTest.exe by connecting it to GEs PDC and your Emulator. The log files look good as long as 10 PMUs are added to stream but after adding eleventh PMU to stream Log reports some error.
Log files are attached herewith for reference.
[Log files for connection to Emulator.zip](https://github.com/ALSETLab/S3DK/files/3186373/Log.files.for.connection.to.Emulator.zip)
[Log files for connection to GEs PDC.zip](https://github.com/ALSETLab/S3DK/files/3186377/Log.files.for.connection.to.GEs.PDC.zip)

**Comment by lvanfretti** [comment]
Thanks @shashankaum 
@Grey-J will try to help me look into this, I’m on travel the next two weeks.

**Comment by shashankaum** [comment]
Finally, the problem has been solved. looking at the error codes we tried to debug the source files in visual studio and after much work we got to the cause of the problem, the BUFFER_SIZE at line 33 of Pdcclient.cpp is set to 4096, once we increased it the S3DK is connecting fine with as many PMUs as we add to the stream. I tried adding 100 PMUs to stream and its working fine. I am attaching the modified Build for reference.
[Release.zip](https://github.com/ALSETLab/S3DK/files/3194073/Release.zip)


Thanks for the nice piece of software.

**Comment by Grey-J** [comment]
@shashankaum 
Sorry to reopen the issue but after looking at the code and trying to follow your work around the error still appears. I've located the buffer size constant your refering to but changing doesn't seem to improve much.
I was wondering what else did you change in order to get it to work?
Thank you for your help

**Comment by shashankaum** [comment]
We have just changed the BUFFER_SIZE at line 33 of Pdcclient.cpp nothing else. I can confirm the problem is resolved, if you want i can send some videos.   
a snapshot of changed constant is attached.
![Bufer size](https://user-images.githubusercontent.com/50229937/58067198-1f390c80-7baa-11e9-966d-efa825a29dca.PNG)

**Comment by shashankaum** [comment]
A video showing connection to stream containing 120 PMUs in PDC simulator.
[bandicam 2019-05-21 09-30-48-058.zip](https://github.com/ALSETLab/S3DK/files/3200732/bandicam.2019-05-21.09-30-48-058.zip)

**Comment by lvanfretti** [comment]
@shashankaum thank you very much! We'll update the DLL repository and update this repository also.
@Grey-J please let me know if you get things to work.

**Comment by Grey-J** [comment]
@shashankaum I was able to get it to work and will upload the fix. Thank you for your help

**Comment by lvanfretti** [comment]
Awesome!
